export const STATUS_TICKET = {
  PENDING: 'PENDING',
  IN_PROGRESS: 'IN_PROGRESS',
  FINISHED: 'FINISHED',
  IGNORED: 'IGNORED',
  RETURN: 'RETURN',
};

export const PRIORITY = {
  HIGH: 'HIGH',
  MEDIUM: 'MEDIUM',
  LOW: 'LOW',
};

export const STATUS_COORDINATOR = {
  TO_DIAGNOSTIQUE: 'TO_DIAGNOSTIQUE',
  TO_REPARE: 'TO_REPARE',
  TO_AFFECT_PRICE: 'TO_AFFECT_PRICE',
};

export const OPEN_DISCOUNT = {
  // TO_DIAGNOSTIQUE: 'TO_DIAGNOSTIQUE',
  ADMIN_TECH: 'ADMIN_TECH',
  ADMIN_MANAGER: 'ADMIN_MANAGER',
};
