export const ROLE = {
  ADMIN_MANAGER: 'ADMIN_MANAGER',
  ADMIN_TECH: 'ADMIN_TECH',
  MANAGER: 'MANAGER',
  TECH: 'TECH',
};

export enum Role {
  ADMIN_MANAGER = 'ADMIN_MANAGER',
  ADMIN_TECH = 'ADMIN_TECH',
  MANAGER = 'MANAGER',
  TECH = 'TECH',
}
